# Generated by Django 5.1.1 on 2024-09-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_usersdog_rename_hello_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdog',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hello.user'),
        ),
        migrations.AlterField(
            model_name='usersdog',
            name='is_bought',
            field=models.BooleanField(verbose_name='Дворовая'),
        ),
    ]
