# Generated by Django 5.1.1 on 2024-09-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_usersdog_user_alter_usersdog_is_bought'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='usersdog',
            options={'verbose_name': 'Собака', 'verbose_name_plural': 'Собаки'},
        ),
    ]
