# Generated by Django 5.1.1 on 2024-09-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_user_options_alter_usersdog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersdog',
            options={'ordering': ['name'], 'verbose_name': 'Собака', 'verbose_name_plural': 'Собаки'},
        ),
        migrations.AddField(
            model_name='usersdog',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='hello/photos', verbose_name='Фото'),
        ),
    ]
